import Head from "next/head";
import { Fragment } from "react";
import ContactInfo from "../components/contact/ContactInfo";
import ContactForm from "../components/contact/ContactForm";
import Footer from "../components/footer/Footer";

function contact() {
  return (
    <Fragment>
      <Head>
        <title>VhonX | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <div className="px-7 max-w-3xl lg:max-w-5xl mx-auto mt-20 h-screen">
        <div className="flex flex-col lg:flex-row space-y-24 lg:items-baseline lg:justify-between lg:space-x-32">
          <ContactInfo />
          <ContactForm />
        </div>
      </div>
      <Footer />
    </Fragment>
  );
}

export default contact;
