import Head from "next/head";
import { Fragment } from "react";
import Footer from "../components/footer/Footer";
import Hero from "../components/home/Hero";
import ReactCourse from "../components/home/ReactCourse";
import Section3 from "../components/home/Section3";
import Section4 from "../components/home/Section4";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>VhonX</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <div className="bg-[url('/vhonx1.0.0/graph-paper.svg')] min-h-screen w-full bg-cover object-cover">
        <div className="space-y-16 lg:space-y-32 px-7 max-w-3xl lg:max-w-5xl mx-auto ">
          <Hero />
          <ReactCourse />
          <Section3 />
          <Section4 />
        </div>
        <Footer />
      </div>
    </Fragment>
  );
}
