import Head from "next/head";
import { Fragment } from "react";

function Team() {
  return (
    <Fragment>
      <Head>
        <title>VhonX</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <h1>team Page</h1>
    </Fragment>
  );
}

export default Team;
